name: Deploy to Tomcat

on:
  push:
    branches:
      - main

env:
  JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Build JAR
        run: |
          ./mvnw clean install
        
      - name: Package JAR
        run: |
          mv target/*.jar .
          git add *.jar
        
      - name: Deploy to Tomcat
        uses: actions/upload-artifact@v2
        with:
          name: application.jar
          path: target/*.jar
          
      - name: Start Tomcat
        uses: actions/start-tomcat@v1
        with:
          tomcat-version: 9.0
          deploy-path: /
          deploy-artifact: application.jar
